#!/bin/sh

#kleuren

rd=$(tput setaf 1) # Red
gr=$(tput setaf 2) # Green
gl=$(tput setaf 3) # Yellow
bl=$(tput setaf 4) # Blue
pa=$(tput setaf 5) # Purple
cy=$(tput setaf 6) # Cyan
wi=$(tput setaf 7) # White
rst=$(tput sgr0) # Text reset.

#vars

version=$(echo Service pi v1.1)
shell=$(lsb_release -a | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $8,$9,$10}' | sed 'N;s/\n/ /;N;s/\n/ /')
arch=$(uname -a | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $13,$16}')
kabel=$( ifconfig | grep -A 1 "eth" | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $7}' | cut -d: -f2 )
wifi=$( ifconfig | grep -A 1 "enx" | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $7}' | cut -d: -f2 )
mem1=$( free | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $8 }' | awk '{ total = $1 / 1024 ; print total }' )
mem2=$( free | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $17}' | awk '{ total = $1 / 1024 ; print total }' )
mem3=$( free | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $16}' | awk '{ total = $1 / 1024 ; print total }')
mem1r=$( printf "%.1f" "$mem1" | awk '{ total = $1 ; print total " MB" }' )
mem2r=$( printf "%.1f" "$mem2" | awk '{ total = $1 ; print total " MB" }' )
mem3r=$( printf "%.1f" "$mem3" | awk '{ total = $1 ; print total " MB" }' )
hdd1=$( df -k . | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $9 }' | awk '{ total = $1 / 1024 / 1024 ; print total }')
hdd2=$( df -k . | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $11}' | awk '{ total = $1 / 1024 / 1024 ; print total }')
hdd3GB=$(  df -k . | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $10}' | awk '{ total = $1 / 1024 /1024 ; print total }')
hdd3=$( df -k . | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $10}' | awk '{ total = $1 / 1024 ; print total }')

hdd1r=$( printf "%.1f" "$hdd1" | awk '{ total = $1 ; print total " GB" }' )
hdd2r=$( printf "%.1f" "$hdd2" | awk '{ total = $1 ; print total " GB" }' )
hdd3r=$( printf "%.1f" "$hdd3" | awk '{ total = $1 ; print total " MB" }' )
hdd3GBR=$( printf "%.1f" "$hdd3GB" | awk '{ total = $1 ; print total " GB" }' )

clear

#commands

echo "${rd}Dit is uw systeem informatie"
echo ${rst}
echo ${gl}Uw versie is ${rst}
echo ${gr}$version
echo ${rst}
echo ${gl}Deze is gebouwd op ${rst}
echo ${gr}$shell
echo ${rst}
echo ${gl}Het processor type is ${rst}
echo ${gr}$arch
echo ${rst}
echo ${gl}Uw ip address via kabel is ${rst}
echo ${gr}$kabel
echo ${rst}
echo ${gl}Uw ip adress via wifi is ${rst}
echo ${gr}$wifi
echo ${rst}
echo ${gl}"Ram geheugen vrij (rood is de hoeveelheid ram er in het systeem is, groen is wat niet gebruikt word,t blauw is wat er momenteel in gebruik is)" ${rst}
echo ${rd}$mem1r ${rst}/ ${gr}$mem2r ${rst}/ ${cy}$mem3r ${rst}
echo
echo ${gl}"Schijfruimte vrij (rood is de hoeveelheid schijfruimte er in het systeem is, groen is wat er nog beschikbaar is, blauw is wat er momenteel in gebruik is)" ${rst}

if [ $hdd3 > 1024 ];
then
echo ${rd}$hdd1r ${rst}/ ${gr}$hdd2r ${rst}/ ${cy}$hdd3GBR ${rst}
echo
echo Gemaakt door ${rd}Patrick Pigmans${rst} voor${cy} Servicenet ITF${rst}
echo
exit 1
fi

if [ $hdd3 < 1024 ];
then
echo ${rd}$hdd1r ${rst}/ ${gr}$hdd2r ${rst}/ ${cy}$hdd3r ${rst}
echo
echo Gemaakt door ${rd}Patrick Pigmans${rst} voor${cy} Servicenet ITF${rst}
echo
exit 1
fi
