#!/bin/sh

#kleuren

rd=$(tput setaf 1) # Red
gr=$(tput setaf 2) # Green
gl=$(tput setaf 3) # Yellow
bl=$(tput setaf 4) # Blue
pa=$(tput setaf 5) # Purple
cy=$(tput setaf 6) # Cyan
wi=$(tput setaf 7) # White
rst=$(tput sgr0) # Text reset.

#vars

version=$(echo Service pi v1.1) # shows version name/laat versie naam zien
shell=$(lsb_release -a | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $8,$9,$10}' | sed 'N;s/\n/ /;N;s/\n/ /') # shows what os and version it was build on/laat zie welke OS en versie deze is op gebouwd
arch=$(uname -a | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $13,$16}') # shows the architecture of the CPU/laat de processor type zien
kabel=$( ifconfig | grep -A 1 "eth" | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $7}' | cut -d: -f2 ) # Shows the IP adress of the ETH* connection (cable) /Laat het ip adress zien van aansluiting ETH* (kabel)
wifi=$( ifconfig | grep -A 1 "enx" | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $7}' | cut -d: -f2 ) # Shows the IP adress of the wlan* connection (cwifi) /Laat het ip adress zien van aansluiting wlan* (wifi)
mem1=$( free | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $8 }' | awk '{ total = $1 / 1024 ; print total }' ) # Calculate total memory/bereken van totaal geheugen
mem2=$( free | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $17}' | awk '{ total = $1 / 1024 ; print total }' ) # Calculate available memory/bereken van resterende geheugen
mem3=$( free | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $16}' | awk '{ total = $1 / 1024 ; print total }')  # Calculate memory usage/bereken van geheugen verbruik
hdd1=$( df -k . | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $9 }' | awk '{ total = $1 / 1024 / 1024 ; print total }') #Calculate total HDD space/berekenen van totale hardeschijf ruimte
hdd2=$( df -k . | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $11}' | awk '{ total = $1 / 1024 / 1024 ; print total }') #Calculate total free HDD space/berekenen van totale vrije hardeschijf ruimte
hdd3GB=$(  df -k . | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $10}' | awk '{ total = $1 / 1024 /1024 ; print total }') # Calculate total used HDD space (GB LINK) / berekenen van totale gebruikte HDD ruimte (link met GB)
hdd3=$( df -k . | sed 'N;s/\n/ /;N;s/\n/ /' | awk '{ print $10}' | awk '{ total = $1 / 1024 ; print total }') # Calculate total used HDD space (MB LINK) / berekenen van totale gebruikte HDD ruimte (link met MB)
mem1r=$( printf "%.1f" "$mem1" | awk '{ total = $1 ; print total " MB" }' ) # Omzetten van kb naar MB
mem2r=$( printf "%.1f" "$mem2" | awk '{ total = $1 ; print total " MB" }' ) # Omzetten van kb naar MB
mem3r=$( printf "%.1f" "$mem3" | awk '{ total = $1 ; print total " MB" }' ) # Omzetten van kb naar MB
hdd1r=$( printf "%.1f" "$hdd1" | awk '{ total = $1 ; print total " GB" }' ) # Omzetten van kb naar GB
hdd2r=$( printf "%.1f" "$hdd2" | awk '{ total = $1 ; print total " GB" }' ) # Omzetten van kb naar GB
hdd3r=$( printf "%.1f" "$hdd3" | awk '{ total = $1 ; print total " MB" }' ) # Omzetten van kb naar MB
hdd3GBR=$( printf "%.1f" "$hdd3GB" | awk '{ total = $1 ; print total " GB" }' ) # Omzetten van kb naar GB





clear

#commands

echo "${rd}Dit is uw systeem informatie"
echo ${rst}
echo ${gl}Uw versie is ${rst}
echo ${gr}$version
echo ${rst}
echo ${gl}Deze is gebouwd op ${rst}
echo ${gr}$shell
echo ${rst}
echo ${gl}Het processor type is ${rst}
echo ${gr}$arch
echo ${rst}
echo ${gl}Uw ip address via kabel is ${rst}
echo ${gr}$kabel
echo ${rst}
echo ${gl}Uw ip adress via wifi is ${rst}
echo ${gr}$wifi
echo ${rst}
echo ${gl}"Ram geheugen vrij (rood is de hoeveelheid ram er in het systeem is, groen is wat niet gebruikt word,t blauw is wat er momenteel in gebruik is)" ${rst}
echo ${rd}$mem1r ${rst}/ ${gr}$mem2r ${rst}/ ${cy}$mem3r ${rst}
echo
echo ${gl}"Schijfruimte vrij (rood is de hoeveelheid schijfruimte er in het systeem is, groen is wat er nog beschikbaar is, blauw is wat er momenteel in gebruik is)" ${rst}

if [ $hdd3 > 1024 ];
then
echo ${rd}$hdd1r ${rst}/ ${gr}$hdd2r ${rst}/ ${cy}$hdd3GBR ${rst}
echo
echo Gemaakt door ${rd}Patrick Pigmans${rst} voor${cy} Servicenet ITF${rst}
echo
exit 1
fi

if [ $hdd3 < 1024 ];
then
echo ${rd}$hdd1r ${rst}/ ${gr}$hdd2r ${rst}/ ${cy}$hdd3r ${rst}
echo
echo Gemaakt door ${rd}Patrick Pigmans${rst} voor${cy} Servicenet ITF${rst}
echo
exit 1
fi
